### ISSUE TITLE
Más información en el README

### ISSUE THREAD

**Issue by FranciscoNaveros** [JA-Gonz/SMS_Estadisticas#1]
Hola.
En el guión de prácticas se especifica lo siguiente:
En la documentación de este hito, que se integrará como el resto en el README.md del proyecto, se explicará por qué se ha elegido el sistema de test y de integración continua.

Además tienes que cumplir 3 objetivos:
3 puntos: Configuración correcta de herramientas de construcción.
5 puntos: Integración continua funcionando.
2 puntos: Tests significativos y/o avance del proyecto en sí más allá de lo básico.

Quiero que me detalles en el README todos los pasos que has seguido para hacer esta práctica y me los justifiques.

**Comment by JA-Gonz** [comment]
¡Hecho!

Muchas gracias por el aviso.
