### ISSUE TITLE
Notas p2

### ISSUE THREAD

**Issue by JA-Gonz** [JA-Gonz/SMS_Estadisticas#3]
Hola @JJ

Tengo unas pequeñas dudas sobre las calificaciones del hito 2 de IV. Acabo de realizar las modificaciones en el repo para arreglar errores de entrega (algunos eran obviedades, que no caí en el momento, que eran para matarme... :/ ). Pero hay un punto en concreto que no entiendo de los comentarios: "Hay muchos typos en el readme". ¿Que quiere decir y como podría arreglarlo?

Intento solventar esto vía GItHub por que me temo que mañana no puedo ir a clase (me sacan una muela, y no se si me han comentado que tu tampoco podrías), y no me gustaría perder ponderación de nota, al dejar pasar otra semana hasta que nos podamos ver de nuevo. ¿Habrá como en el hito 1 "peticiones" de revisión?

¡Muchas gracias por todo!

**Comment by JJ** [comment]
Son errores tipográfficos, faltas de ortografía o errores al teclear. Por
favor, revísalo; no te digo que le pases un corrector ortográfico, pero
esaría bien. No te preocupes por la ponderación, se baja cada fecha de
corte, no automáticamente cada semana.
